export * from './user.model';
export * from './default-response.model';
export * from './default-user-response.model';
export * from './residence.model';
export * from './resident.model';
export * from './visitor.model';
export * from './type-visit.model';
export * from './visit.model';
export * from './auth.model';
export * from './user-type.model'
